import library

In [3]:
import numpy as np
import pandas as pd

In [4]:
filename = "C:/Users/faiz_/Desktop/JupyterNotebook/train.csv"

import excelfile into a variable traindf

In [5]:
traindf = pd.read_csv(filename)

set options for pandas dataframe

In [6]:
#pd.set_option('display.max_rows', 1460)
#pd.set_option('display.max_columns', 81)

print the data types of each columns

In [7]:
print(traindf.dtypes)

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

print the total range of traindf

In [8]:
print(traindf.index)

RangeIndex(start=0, stop=1460, step=1)

print the column name for traindf

In [9]:
print(traindf.columns)

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

print the values of traindf dataset

In [ ]:
print(traindf.values)

print the first value of traindf dataset

In [ ]:
print(traindf.values[0])

print the important stats of the dataset such as mean,std deviation, min,max, percentile(1,median,3)

In [11]:
print(traindf.describe())

                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000
mean     94.244521    46.660274      21.954110     3.409589    15.060959
std     125.338794    66.256028      61.119149    29.317331    55.757415
min       0.000000     0.000000       0.000000     0.000000     0.000000
25%       0.000000     0.000000       0.000000     0.000000     0.000000
50%       0.000000    25.000000       0.000000     0.000000     0.000000
75%     168.000000    68.000000       0.000000     0.000000     0.000000
max     857.000000   547.000000     552.000000   508.000000   480.000000

          PoolArea       MiscVal       MoSold       YrSold      SalePrice
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890
std      40.177307    496.123024     2.703626     1.328095   79442.502883
min       0.000000      0.000000     1.000000  2006.000000   34900.000000
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000

[8 rows x 38 columns]

show a list of information on the dataframe such as datatypes, total data in the each column, null/non-null data

In [12]:
print(traindf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB
None

sort data by the highest value on the given column

In [13]:
print(traindf.sort_values("SalePrice", ascending=False))

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
691    692          60       RL        104.0    21535   Pave   NaN      IR1
1182  1183          60       RL        160.0    15623   Pave   NaN      IR1
1169  1170          60       RL        118.0    35760   Pave   NaN      IR1
898    899          20       RL        100.0    12919   Pave   NaN      IR1
803    804          60       RL        107.0    13891   Pave   NaN      Reg
...    ...         ...      ...          ...      ...    ...   ...      ...
30      31          70  C (all)         50.0     8500   Pave  Pave      Reg
533    534          20       RL         50.0     5000   Pave   NaN      Reg
968    969          50       RM         50.0     5925   Pave   NaN      Reg
916    917          20  C (all)         50.0     9000   Pave   NaN      Reg
495    496          30  C (all)         60.0     7879   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
691          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1182         Lvl    AllPub  ...      555     Ex  MnPrv         NaN       0
1169         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
898          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
803          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
...          ...       ...  ...      ...    ...    ...         ...     ...
30           Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
533          Low    AllPub  ...        0    NaN    NaN         NaN       0
968          Lvl    AllPub  ...        0    NaN   GdWo         NaN       0
916          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
495          Lvl    AllPub  ...        0    NaN   GdWo         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
691       1   2007        WD         Normal     755000
1182      7   2007        WD        Abnorml     745000
1169      7   2006        WD         Normal     625000
898       3   2010       New        Partial     611657
803       1   2009       New        Partial     582933
...     ...    ...       ...            ...        ...
30        7   2008        WD         Normal      40000
533       1   2007        WD         Normal      39300
968       5   2009        WD        Abnorml      37900
916      10   2006        WD        Abnorml      35311
495      11   2009        WD        Abnorml      34900

[1460 rows x 81 columns]

print value for the given column

In [14]:
print(traindf.SalePrice)
#print(traindf['SalePrice'])

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

print value for dataset from index 490-500(slicing)

In [15]:
print(traindf[490:500])

      Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
490  491         160       RM          NaN     2665   Pave   NaN      Reg
491  492          50       RL         79.0     9490   Pave   NaN      Reg
492  493          60       RL        105.0    15578   Pave   NaN      IR1
493  494          20       RL         70.0     7931   Pave   NaN      Reg
494  495          30       RM         50.0     5784   Pave   NaN      Reg
495  496          30  C (all)         60.0     7879   Pave   NaN      Reg
496  497          20       RL          NaN    12692   Pave   NaN      IR1
497  498          50       RL         60.0     9120   Pave  Pave      Reg
498  499          20       RL         65.0     7800   Pave   NaN      Reg
499  500          20       RL         70.0     7535   Pave   NaN      IR1

    LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
490         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
491         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
492         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
493         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
494         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
495         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0
496         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
497         Lvl    AllPub  ...        0    NaN  GdPrv         NaN       0
498         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
499         Lvl    AllPub  ...        0    NaN   MnWw        Shed     480

    MoSold YrSold  SaleType  SaleCondition  SalePrice
490      6   2008        WD         Normal     115000
491      8   2006        WD         Normal     133000
492      5   2006       New        Partial     172785
493      6   2008        WD         Normal     155000
494     12   2009        WD         Normal      91300
495     11   2009        WD        Abnorml      34900
496      5   2007        WD         Normal     430000
497      6   2008        WD         Normal     184000
498      6   2009        WD         Normal     130000
499      6   2007        WD         Normal     120000

[10 rows x 81 columns]

print dataset with given column(multiple)

In [18]:
print(traindf[['YrSold','SalePrice']])

      YrSold  SalePrice
0       2008     208500
1       2007     181500
2       2008     223500
3       2006     140000
4       2008     250000
...      ...        ...
1455    2007     175000
1456    2010     210000
1457    2010     266500
1458    2010     142125
1459    2008     147500

[1460 rows x 2 columns]

loc is label based (take dataset from label), iloc is integer based(take dataset using integer)

print traindf dataset from index 490-510 with given column names

In [19]:
print(traindf.loc[490:510,['YrSold','SalePrice']])

     YrSold  SalePrice
490    2008     115000
491    2006     133000
492    2006     172785
493    2008     155000
494    2009      91300
495    2009      34900
496    2007     430000
497    2008     184000
498    2009     130000
499    2007     120000
500    2007     113000
501    2008     226700
502    2007     140000
503    2010     289000
504    2009     147000
505    2009     124500
506    2006     215000
507    2009     208300
508    2008     161000
509    2009     124500
510    2009     164900

print traindf data from given row(9) and given column(SalePrice)

In [20]:
print(traindf.loc[9,['SalePrice']])

SalePrice    118000
Name: 9, dtype: object

print traindf data from range 490-510 and column 77-80

In [21]:
print(traindf.iloc[490:510,[77,80]])

     YrSold  SalePrice
490    2008     115000
491    2006     133000
492    2006     172785
493    2008     155000
494    2009      91300
495    2009      34900
496    2007     430000
497    2008     184000
498    2009     130000
499    2007     120000
500    2007     113000
501    2008     226700
502    2007     140000
503    2010     289000
504    2009     147000
505    2009     124500
506    2006     215000
507    2009     208300
508    2008     161000
509    2009     124500

print all data from traindf where SalePrice is smaller than 50000

In [22]:
print(traindf[traindf.SalePrice <50000])

      Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
30    31          70  C (all)         50.0     8500   Pave  Pave      Reg
495  496          30  C (all)         60.0     7879   Pave   NaN      Reg
533  534          20       RL         50.0     5000   Pave   NaN      Reg
916  917          20  C (all)         50.0     9000   Pave   NaN      Reg
968  969          50       RM         50.0     5925   Pave   NaN      Reg

    LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
30          Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
495         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0
533         Low    AllPub  ...        0    NaN    NaN         NaN       0
916         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
968         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0

    MoSold YrSold  SaleType  SaleCondition  SalePrice
30       7   2008        WD         Normal      40000
495     11   2009        WD        Abnorml      34900
533      1   2007        WD         Normal      39300
916     10   2006        WD        Abnorml      35311
968      5   2009        WD        Abnorml      37900

[5 rows x 81 columns]

filter traindf data through given column(RoofStyle) where variable(Gable and Hip) is in the dataset

In [ ]:
print(traindf[traindf.RoofStyle.isin(['Gable','Hip'])])

assign 10000 to given row(0) and given column(SalePrice)

In [24]:
traindf.loc[0,['SalePrice']] = 10000

print traindf values for row 0

In [25]:
print(traindf.values[0])

[1 60 'RL' 65.0 8450 'Pave' nan 'Reg' 'Lvl' 'AllPub' 'Inside' 'Gtl'
 'CollgCr' 'Norm' 'Norm' '1Fam' '2Story' 7 5 2003 2003 'Gable' 'CompShg'
 'VinylSd' 'VinylSd' 'BrkFace' 196.0 'Gd' 'TA' 'PConc' 'Gd' 'TA' 'No'
 'GLQ' 706 'Unf' 0 150 856 'GasA' 'Ex' 'Y' 'SBrkr' 856 854 0 1710 1 0 2 1
 3 1 'Gd' 8 'Typ' 0 nan 'Attchd' 2003.0 'RFn' 2 548 'TA' 'TA' 'Y' 0 61 0 0
 0 0 nan nan nan 0 2 2008 'WD' 'Normal' 10000]

print the top 20 row of traindf datasets

In [26]:
print(traindf.head(20))

    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg
1    2          20       RL         80.0     9600   Pave   NaN      Reg
2    3          60       RL         68.0    11250   Pave   NaN      IR1
3    4          70       RL         60.0     9550   Pave   NaN      IR1
4    5          60       RL         84.0    14260   Pave   NaN      IR1
5    6          50       RL         85.0    14115   Pave   NaN      IR1
6    7          20       RL         75.0    10084   Pave   NaN      Reg
7    8          60       RL          NaN    10382   Pave   NaN      IR1
8    9          50       RM         51.0     6120   Pave   NaN      Reg
9   10         190       RL         50.0     7420   Pave   NaN      Reg
10  11          20       RL         70.0    11200   Pave   NaN      Reg
11  12          60       RL         85.0    11924   Pave   NaN      IR1
12  13          20       RL          NaN    12968   Pave   NaN      IR2
13  14          20       RL         91.0    10652   Pave   NaN      IR1
14  15          20       RL          NaN    10920   Pave   NaN      IR1
15  16          45       RM         51.0     6120   Pave   NaN      Reg
16  17          20       RL          NaN    11241   Pave   NaN      IR1
17  18          90       RL         72.0    10791   Pave   NaN      Reg
18  19          20       RL         66.0    13695   Pave   NaN      Reg
19  20          20       RL         70.0     7560   Pave   NaN      Reg

   LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
2          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
3          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
4          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
5          Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700
6          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
7          Lvl    AllPub  ...        0    NaN    NaN        Shed     350
8          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
9          Lvl    AllPub  ...        0    NaN    NaN         NaN       0
10         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
11         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
12         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
13         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
14         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0
15         Lvl    AllPub  ...        0    NaN  GdPrv         NaN       0
16         Lvl    AllPub  ...        0    NaN    NaN        Shed     700
17         Lvl    AllPub  ...        0    NaN    NaN        Shed     500
18         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
19         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0

   MoSold YrSold  SaleType  SaleCondition  SalePrice
0       2   2008        WD         Normal      10000
1       5   2007        WD         Normal     181500
2       9   2008        WD         Normal     223500
3       2   2006        WD        Abnorml     140000
4      12   2008        WD         Normal     250000
5      10   2009        WD         Normal     143000
6       8   2007        WD         Normal     307000
7      11   2009        WD         Normal     200000
8       4   2008        WD        Abnorml     129900
9       1   2008        WD         Normal     118000
10      2   2008        WD         Normal     129500
11      7   2006       New        Partial     345000
12      9   2008        WD         Normal     144000
13      8   2007       New        Partial     279500
14      5   2008        WD         Normal     157000
15      7   2007        WD         Normal     132000
16      3   2010        WD         Normal     149000
17     10   2006        WD         Normal      90000
18      6   2008        WD         Normal     159000
19      5   2009       COD        Abnorml     139000

[20 rows x 81 columns]

rename column name Saleprice to saleprice

In [27]:
traindf = traindf.rename(columns= {'SalePrice':'saleprice'})

print all dataset from traindf in row(YrSold and saleprice) through iteration

In [28]:
for i, row in traindf.iterrows():
    print(i, row['YrSold'], row['saleprice'])

0 2008 10000
1 2007 181500
2 2008 223500
3 2006 140000
4 2008 250000
5 2009 143000
6 2007 307000
7 2009 200000
8 2008 129900
9 2008 118000
10 2008 129500
11 2006 345000
12 2008 144000
13 2007 279500
14 2008 157000
15 2007 132000
16 2010 149000
17 2006 90000
18 2008 159000
19 2009 139000
20 2006 325300
21 2007 139400
22 2008 230000
23 2007 129900
24 2010 154000
25 2009 256300
26 2010 134800
27 2010 306000
28 2006 207500
29 2008 68500
30 2008 40000
31 2008 149350
32 2008 179900
33 2010 165500
34 2007 277500
35 2006 309000
36 2009 145000
37 2009 153000
38 2010 109000
39 2008 82000
40 2006 160000
41 2007 170000
42 2007 144000
43 2008 130250
44 2006 141000
45 2010 319900
46 2009 239686
47 2007 249700
48 2009 113000
49 2007 127000
50 2007 177000
51 2006 114500
52 2010 110000
53 2006 385000
54 2007 130000
55 2008 180500
56 2009 172500
57 2006 196500
58 2006 438780
59 2008 124900
60 2006 158000
61 2007 101000
62 2007 202500
63 2010 140000
64 2009 219500
65 2007 317000
66 2010 180000
67 2007 226000
68 2010 80000
69 2006 225000
70 2007 244000
71 2007 129500
72 2009 185000
73 2010 144900
74 2010 107400
75 2009 91000
76 2008 135750
77 2008 127000
78 2010 136500
79 2009 110000
80 2009 193500
81 2006 153500
82 2008 245000
83 2007 126500
84 2009 168500
85 2006 260000
86 2009 174000
87 2009 164500
88 2009 85000
89 2007 123600
90 2006 109900
91 2006 98600
92 2009 163500
93 2007 133900
94 2007 204750
95 2009 185000
96 2006 214000
97 2007 94750
98 2010 83000
99 2010 128950
100 2010 205000
101 2010 178000
102 2009 118964
103 2010 198900
104 2007 169500
105 2008 250000
106 2007 100000
107 2008 115000
108 2007 115000
109 2010 190000
110 2006 136900
111 2010 180000
112 2007 383970
113 2007 217000
114 2007 259500
115 2007 176000
116 2009 139000
117 2007 155000
118 2010 320000
119 2006 163990
120 2006 180000
121 2007 100000
122 2008 136000
123 2008 153900
124 2009 181000
125 2006 84500
126 2007 128000
127 2007 87000
128 2006 155000
129 2006 150000
130 2006 226000
131 2009 244000
132 2007 150750
133 2009 220000
134 2006 180000
135 2008 174000
136 2007 143000
137 2006 171000
138 2008 230000
139 2009 231500
140 2010 115000
141 2006 260000
142 2010 166000
143 2009 204000
144 2006 125000
145 2006 130000
146 2009 105000
147 2010 222500
148 2008 141000
149 2006 115000
150 2007 122000
151 2008 372402
152 2006 190000
153 2008 235000
154 2006 125000
155 2008 79000
156 2006 109500
157 2010 269500
158 2010 254900
159 2006 320000
160 2008 162500
161 2008 412500
162 2010 220000
163 2007 103200
164 2007 152000
165 2008 127500
166 2009 190000
167 2007 325624
168 2007 183500
169 2006 228000
170 2007 128500
171 2010 215000
172 2006 239000
173 2008 163000
174 2008 184000
175 2007 243000
176 2007 211000
177 2006 172500
178 2009 501837
179 2007 100000
180 2007 177000
181 2006 200100
182 2007 120000
183 2008 200000
184 2006 127000
185 2006 475000
186 2009 173000
187 2009 135000
188 2009 153337
189 2008 286000
190 2007 315000
191 2007 184000
192 2009 192000
193 2006 130000
194 2008 127000
195 2009 148500
196 2007 311872
197 2006 235000
198 2009 104000
199 2009 274900
200 2010 140000
201 2008 171500
202 2006 112000
203 2008 149000
204 2009 110000
205 2009 180500
206 2007 143900
207 2008 141000
208 2007 277000
209 2008 145000
210 2008 98000
211 2010 186000
212 2009 252678
213 2006 156000
214 2010 161750
215 2006 134450
216 2008 210000
217 2006 107000
218 2008 311500
219 2006 167240
220 2006 204900
221 2009 200000
222 2006 179900
223 2009 97000
224 2009 386250
225 2009 112000
226 2007 290000
227 2008 106000
228 2010 125000
229 2009 192500
230 2010 148000
231 2009 403000
232 2006 94500
233 2010 128200
234 2010 216500
235 2008 89500
236 2010 185500
237 2010 194500
238 2007 318000
239 2010 113000
240 2010 262500
241 2007 110500
242 2006 79000
243 2009 120000
244 2010 205000
245 2006 241500
246 2006 137000
247 2006 140000
248 2007 180000
249 2007 277000
250 2010 76500
251 2007 235000
252 2008 173000
253 2007 158000
254 2010 145000
255 2006 230000
256 2008 207500
257 2009 220000
258 2008 231500
259 2008 97000
260 2009 176000
261 2007 276000
262 2006 151000
263 2010 130000
264 2008 73000
265 2008 175500
266 2006 185000
267 2008 179500
268 2008 120500
269 2007 148000
270 2006 266000
271 2008 241500
272 2010 290000
273 2009 139000
274 2007 124500
275 2009 205000
276 2010 201000
277 2010 141000
278 2007 415298
279 2008 192000
280 2007 228500
281 2006 185000
282 2009 207500
283 2009 244600
284 2007 179200
285 2007 164700
286 2006 159000
287 2006 88000
288 2010 122000
289 2007 153575
290 2006 233230
291 2008 135900
292 2009 131000
293 2006 235000
294 2009 167000
295 2006 142500
296 2007 152000
297 2007 239000
298 2007 175000
299 2009 158500
300 2006 157000
301 2007 267000
302 2006 205000
303 2006 149900
304 2008 295000
305 2007 305900
306 2007 225000
307 2008 89500
308 2009 82500
309 2006 360000
310 2006 165600
311 2009 132000
312 2006 119900
313 2009 375000
314 2006 178000
315 2009 188500
316 2009 260000
317 2007 270000
318 2009 260000
319 2009 187500
320 2006 342643
321 2007 354000
322 2007 301000
323 2006 126175
324 2010 242000
325 2007 87000
326 2008 324000
327 2006 145250
328 2009 214500
329 2009 78000
330 2007 119000
331 2007 139000
332 2009 284000
333 2008 207000
334 2008 192000
335 2008 228950
336 2007 377426
337 2008 214000
338 2006 202500
339 2009 155000
340 2010 202900
341 2009 82000
342 2006 87500
343 2008 266000
344 2010 85000
345 2006 140200
346 2007 151500
347 2009 157500
348 2008 154000
349 2006 437154
350 2007 318061
351 2006 190000
352 2008 95000
353 2010 105900
354 2006 140000
355 2007 177500
356 2009 173000
357 2007 134000
358 2006 130000
359 2006 280000
360 2007 156000
361 2008 145000
362 2009 198500
363 2009 118000
364 2006 190000
365 2009 147000
366 2009 159000
367 2008 165000
368 2010 132000
369 2010 162000
370 2006 172400
371 2008 134432
372 2010 125000
373 2009 123000
374 2007 219500
375 2009 61000
376 2006 148000
377 2007 340000
378 2010 394432
379 2009 179000
380 2010 127000
381 2006 187750
382 2007 213500
383 2009 76000
384 2007 240000
385 2010 192000
386 2006 81000
387 2009 125000
388 2008 191000
389 2008 426000
390 2008 119000
391 2009 215000
392 2007 106500
393 2006 100000
394 2007 109000
395 2010 129000
396 2009 123000
397 2007 169500
398 2007 67000
399 2009 241000
400 2008 245500
401 2006 164990
402 2008 108000
403 2006 258000
404 2007 168000
405 2009 150000
406 2008 115000
407 2008 177000
408 2007 280000
409 2008 339750
410 2009 60000
411 2006 145000
412 2010 222000
413 2010 115000
414 2008 228000
415 2007 181134
416 2006 149500
417 2007 239000
418 2007 126000
419 2010 142000
420 2008 206300
421 2009 215000
422 2008 113000
423 2008 315000
424 2008 139000
425 2009 135000
426 2009 275000
427 2008 109008
428 2007 195400
429 2009 175000
430 2008 85400
431 2008 79900
432 2007 122500
433 2008 181000
434 2008 81000
435 2009 212000
436 2006 116000
437 2009 119000
438 2007 90350
439 2009 110000
440 2009 555000
441 2008 118000
442 2008 162900
443 2007 172500
444 2008 210000
445 2009 127500
446 2010 190000
447 2006 199900
448 2006 119500
449 2007 120000
450 2006 110000
451 2006 280000
452 2007 204000
453 2009 210000
454 2006 188000
455 2007 175500
456 2008 98000
457 2008 256000
458 2008 161000
459 2009 110000
460 2009 263435
461 2009 155000
462 2009 62383
463 2008 188700
464 2009 124000
465 2006 178740
466 2007 167000
467 2007 146500
468 2007 250000
469 2008 187000
470 2010 212000
471 2007 190000
472 2008 148000
473 2007 440000
474 2007 251000
475 2007 132500
476 2008 208900
477 2007 380000
478 2009 297000
479 2007 89471
480 2006 326000
481 2006 374000
482 2009 155000
483 2006 164000
484 2007 132500
485 2009 147000
486 2007 156000
487 2007 175000
488 2006 160000
489 2009 86000
490 2008 115000
491 2006 133000
492 2006 172785
493 2008 155000
494 2009 91300
495 2009 34900
496 2007 430000
497 2008 184000
498 2009 130000
499 2007 120000
500 2007 113000
501 2008 226700
502 2007 140000
503 2010 289000
504 2009 147000
505 2009 124500
506 2006 215000
507 2009 208300
508 2008 161000
509 2009 124500
510 2009 164900
511 2006 202665
512 2006 129900
513 2007 134000
514 2007 96500
515 2009 402861
516 2009 158000
517 2009 265000
518 2007 211000
519 2009 234000
520 2008 106250
521 2007 150000
522 2006 159000
523 2007 184750
524 2007 315750
525 2006 176000
526 2007 132000
527 2008 446261
528 2007 86000
529 2007 200624
530 2008 175000
531 2008 128000
532 2010 107500
533 2007 39300
534 2006 178000
535 2008 107500
536 2008 188000
537 2008 111250
538 2006 158000
539 2010 272000
540 2009 315000
541 2007 248000
542 2009 213250
543 2007 133000
544 2006 179665
545 2006 229000
546 2007 210000
547 2007 129500
548 2008 125000
549 2009 263000
550 2008 140000
551 2008 112500
552 2009 255500
553 2009 108000
554 2008 284000
555 2006 113000
556 2006 141000
557 2006 108000
558 2008 175000
559 2006 234000
560 2010 121500
561 2006 170000
562 2008 108000
563 2008 185000
564 2006 268000
565 2010 128000
566 2008 325000
567 2010 214000
568 2009 316600
569 2006 135960
570 2008 142600
571 2006 120000
572 2009 224500
573 2007 170000
574 2007 139000
575 2008 118500
576 2009 145000
577 2006 164500
578 2008 146000
579 2008 131500
580 2007 181900
581 2009 253293
582 2007 118500
583 2008 325000
584 2009 133000
585 2006 369900
586 2008 130000
587 2009 137000
588 2009 143000
589 2008 79500
590 2008 185900
591 2009 451950
592 2008 138000
593 2009 140000
594 2008 110000
595 2006 319000
596 2006 114504
597 2007 194201
598 2006 217500
599 2008 151000
600 2006 275000
601 2007 141000
602 2006 220000
603 2010 151000
604 2008 221000
605 2009 205000
606 2009 152000
607 2006 225000
608 2007 359100
609 2007 118500
610 2009 313000
611 2007 148000
612 2009 261500
613 2007 147000
614 2010 75500
615 2010 137500
616 2006 183200
617 2008 105500
618 2007 314813
619 2008 305000
620 2008 67000
621 2008 240000
622 2009 135000
623 2007 168500
624 2006 165150
625 2010 160000
626 2007 139900
627 2010 153000
628 2007 135000
629 2008 168500
630 2006 124000
631 2007 209500
632 2009 82500
633 2007 139400
634 2010 144000
635 2007 200000
636 2009 60000
637 2009 93000
638 2008 85000
639 2006 264561
640 2008 274000
641 2007 226000
642 2009 345000
643 2007 152000
644 2009 370878
645 2007 143250
646 2008 98300
647 2008 155000
648 2010 155000
649 2007 84500
650 2008 205950
651 2009 108000
652 2009 191000
653 2008 135000
654 2008 350000
655 2010 88000
656 2008 145500
657 2008 149000
658 2010 97500
659 2009 167000
660 2007 197900
661 2009 402000
662 2009 110000
663 2008 137500
664 2006 423000
665 2006 230500
666 2007 129000
667 2008 193500
668 2006 168000
669 2006 137500
670 2009 173500
671 2009 103600
672 2006 165000
673 2007 257500
674 2008 140000
675 2009 148500
676 2006 87000
677 2009 109500
678 2009 372500
679 2007 128500
680 2010 143000
681 2009 159434
682 2008 173000
683 2007 285000
684 2010 221000
685 2007 207500
686 2007 227875
687 2007 148800
688 2007 392000
689 2007 194700
690 2008 141000
691 2007 755000
692 2006 335000
693 2006 108480
694 2009 141500
695 2006 176000
696 2006 89000
697 2006 123500
698 2010 138500
699 2008 196000
700 2006 312500
701 2006 140000
702 2006 361919
703 2010 140000
704 2010 213000
705 2010 55000
706 2007 302000
707 2009 254000
708 2007 179540
709 2008 109900
710 2008 52000
711 2010 102776
712 2008 189000
713 2006 129000
714 2010 130500
715 2009 165000
716 2007 159500
717 2008 157000
718 2008 341000
719 2006 128500
720 2006 275000
721 2010 143000
722 2009 124500
723 2008 135000
724 2009 320000
725 2009 120500
726 2009 222000
727 2009 194500
728 2009 110000
729 2009 103000
730 2010 236500
731 2007 187500
732 2008 222500
733 2009 131400
734 2007 108000
735 2006 163000
736 2006 93500
737 2006 239900
738 2009 179000
739 2009 190000
740 2007 132000
741 2008 142000
742 2007 179000
743 2009 175000
744 2008 180000
745 2008 299800
746 2009 236000
747 2009 265979
748 2010 260400
749 2009 98000
750 2010 96500
751 2007 162000
752 2006 217000
753 2006 275500
754 2009 156000
755 2009 172500
756 2009 212000
757 2010 158900
758 2008 179400
759 2007 290000
760 2009 127500
761 2009 100000
762 2010 215200
763 2009 337000
764 2006 270000
765 2008 264132
766 2010 196500
767 2008 160000
768 2006 216837
769 2010 538000
770 2009 134900
771 2006 102000
772 2010 107000
773 2007 114500
774 2007 395000
775 2009 162000
776 2006 221500
777 2006 142500
778 2007 144000
779 2006 135000
780 2007 176000
781 2006 175900
782 2009 187100
783 2009 165500
784 2008 128000
785 2009 161500
786 2010 139000
787 2010 233000
788 2008 107900
789 2007 187500
790 2009 160200
791 2007 146800
792 2007 269790
793 2007 225000
794 2008 194500
795 2010 171000
796 2007 143500
797 2008 110000
798 2009 485000
799 2007 175000
800 2008 200000
801 2007 109900
802 2008 189000
803 2009 582933
804 2006 118000
805 2008 227680
806 2006 135500
807 2009 223500
808 2006 159950
809 2009 106000
810 2006 181000
811 2008 144500
812 2010 55993
813 2007 157900
814 2006 116000
815 2010 224900
816 2006 137000
817 2008 271000
818 2010 155000
819 2010 224000
820 2008 183000
821 2009 93000
822 2007 225000
823 2009 139500
824 2006 232600
825 2008 385000
826 2008 109500
827 2009 189000
828 2009 185000
829 2006 147400
830 2008 166000
831 2006 151000
832 2010 237000
833 2009 167000
834 2008 139950
835 2010 128000
836 2007 153500
837 2008 100000
838 2008 144000
839 2008 130500
840 2008 140000
841 2008 157500
842 2008 174900
843 2007 141000
844 2008 153900
845 2007 171000
846 2009 213000
847 2009 133500
848 2008 240000
849 2007 187000
850 2007 131500
851 2006 215000
852 2007 164000
853 2009 158000
854 2006 170000
855 2010 127000
856 2008 147000
857 2009 174000
858 2009 152000
859 2006 250000
860 2007 189950
861 2010 131500
862 2010 152000
863 2009 132500
864 2008 250580
865 2009 148500
866 2007 248900
867 2007 129000
868 2006 169000
869 2010 236000
870 2009 109500
871 2010 200500
872 2008 116000
873 2009 133000
874 2009 66500
875 2007 303477
876 2007 132250
877 2009 350000
878 2010 148000
879 2009 136500
880 2007 157000
881 2007 187500
882 2009 178000
883 2006 118500
884 2009 100000
885 2008 328900
886 2006 145000
887 2008 135500
888 2007 268000
889 2009 149500
890 2007 122900
891 2009 172500
892 2006 154500
893 2008 165000
894 2009 118858
895 2008 140000
896 2006 106500
897 2009 142953
898 2010 611657
899 2006 135000
900 2007 110000
901 2009 153000
902 2006 180000
903 2006 240000
904 2007 125500
905 2010 128000
906 2007 255000
907 2006 250000
908 2006 131000
909 2009 174000
910 2010 154300
911 2009 143500
912 2006 88000
913 2007 145000
914 2009 173733
915 2007 75000
916 2006 35311
917 2009 135000
918 2007 238000
919 2008 176500
920 2007 201000
921 2008 145900
922 2006 169990
923 2008 193000
924 2006 207500
925 2008 175000
926 2007 285000
927 2008 176000
928 2009 236500
929 2006 222000
930 2009 201000
931 2009 117500
932 2007 320000
933 2009 190000
934 2008 242000
935 2006 79900
936 2009 184900
937 2009 253000
938 2006 239799
939 2010 244400
940 2006 150900
941 2009 214000
942 2007 150000
943 2007 143000
944 2009 137500
945 2009 124900
946 2006 143000
947 2007 270000
948 2006 192500
949 2010 197500
950 2007 129000
951 2006 119900
952 2009 133900
953 2008 172000
954 2006 127500
955 2007 145000
956 2009 124000
957 2007 132000
958 2007 185000
959 2010 155000
960 2010 116500
961 2008 272000
962 2007 155000
963 2009 239000

964 2010 214900
965 2007 178900
966 2009 160000
967 2008 135000
968 2009 37900
969 2006 140000
970 2006 135000
971 2009 173000
972 2010 99500
973 2008 182000
974 2009 167500
975 2006 165000
976 2006 85500
977 2007 199900
978 2007 110000
979 2009 139000
980 2008 178400
981 2009 336000
982 2008 159895
983 2008 255900
984 2009 126000
985 2008 125000
986 2006 117000
987 2010 395192
988 2007 195000
989 2006 197000
990 2006 348000
991 2009 168000
992 2007 187000
993 2006 173900
994 2009 337500
995 2006 121600
996 2006 136500
997 2009 185000
998 2006 91000
999 2010 206000
1000 2009 82000
1001 2007 86000
1002 2008 232000
1003 2007 136905
1004 2009 181000
1005 2008 149900
1006 2007 163500
1007 2009 88000
1008 2009 240000
1009 2006 102000
1010 2008 135000
1011 2010 100000
1012 2007 165000
1013 2009 85000
1014 2007 119200
1015 2009 227000
1016 2009 203000
1017 2009 187500
1018 2007 160000
1019 2006 213490
1020 2008 176000
1021 2006 194000
1022 2007 87000
1023 2008 191000
1024 2008 287000
1025 2007 112500
1026 2010 167500
1027 2008 293077
1028 2007 105000
1029 2006 118000
1030 2006 160000
1031 2009 197000
1032 2006 310000
1033 2006 230000
1034 2007 119750
1035 2009 84000
1036 2009 315500
1037 2008 287000
1038 2009 97000
1039 2009 80000
1040 2006 155000
1041 2008 173000
1042 2009 196000
1043 2008 262280
1044 2009 278000
1045 2009 139600
1046 2006 556581
1047 2008 145000
1048 2009 115000
1049 2010 84900
1050 2007 176485
1051 2007 200141
1052 2007 165000
1053 2010 144500
1054 2006 255000
1055 2008 180000
1056 2006 185850
1057 2009 248000
1058 2009 335000
1059 2007 220000
1060 2010 213500
1061 2008 81000
1062 2007 90000
1063 2006 110500
1064 2009 154000
1065 2010 328000
1066 2009 178000
1067 2008 167900
1068 2006 151400
1069 2007 135000
1070 2007 135000
1071 2009 154000
1072 2006 91500
1073 2009 159500
1074 2007 194000
1075 2007 219500
1076 2006 170000
1077 2006 138800
1078 2006 155900
1079 2007 126000
1080 2008 145000
1081 2010 133000
1082 2007 192000
1083 2006 160000
1084 2006 187500
1085 2010 147000
1086 2010 83500
1087 2009 252000
1088 2006 137500
1089 2006 197000
1090 2009 92900
1091 2008 160000
1092 2008 136500
1093 2006 146000
1094 2010 129000
1095 2007 176432
1096 2007 127000
1097 2007 170000
1098 2009 128000
1099 2009 157000
1100 2009 60000
1101 2007 119500
1102 2007 135000
1103 2006 159500
1104 2007 106000
1105 2010 325000
1106 2007 179900
1107 2006 274725
1108 2007 181000
1109 2009 280000
1110 2008 188000
1111 2008 205000
1112 2006 129900
1113 2007 134500
1114 2006 117000
1115 2007 318000
1116 2009 184100
1117 2008 130000
1118 2008 140000
1119 2006 133700
1120 2007 118400
1121 2006 212900
1122 2009 112000
1123 2009 118000
1124 2007 163900
1125 2009 115000
1126 2009 174000
1127 2007 259000
1128 2007 215000
1129 2007 140000
1130 2009 135000
1131 2007 93500
1132 2007 117500
1133 2009 239500
1134 2007 169000
1135 2007 102000
1136 2008 119000
1137 2010 94000
1138 2009 196000
1139 2007 144000
1140 2008 139000
1141 2009 197500
1142 2007 424870
1143 2008 80000
1144 2010 80000
1145 2006 149000
1146 2006 180000
1147 2009 174500
1148 2008 116900
1149 2009 143000
1150 2007 124000
1151 2006 149900
1152 2006 230000
1153 2008 120500
1154 2008 201800
1155 2007 218000
1156 2008 179900
1157 2009 230000
1158 2008 235128
1159 2008 185000
1160 2010 146000
1161 2008 224000
1162 2007 129000
1163 2008 108959
1164 2007 194000
1165 2009 233170
1166 2010 245350
1167 2006 173000
1168 2008 235000
1169 2006 625000
1170 2008 171000
1171 2008 163000
1172 2008 171900
1173 2007 200500
1174 2006 239000
1175 2007 285000
1176 2008 119500
1177 2009 115000
1178 2009 154900
1179 2006 93000
1180 2006 250000
1181 2008 392500
1182 2007 745000
1183 2006 120000
1184 2007 186700
1185 2006 104900
1186 2009 95000
1187 2006 262000
1188 2009 195000
1189 2010 189000
1190 2007 168000
1191 2007 174000
1192 2007 125000
1193 2009 165000
1194 2010 158000
1195 2008 176000
1196 2006 219210
1197 2006 144000
1198 2009 178000
1199 2006 148000
1200 2006 116050
1201 2009 197900
1202 2009 117000
1203 2009 213000
1204 2006 153500
1205 2009 271900
1206 2006 107000
1207 2006 200000
1208 2008 140000
1209 2006 290000
1210 2010 189000
1211 2010 164000
1212 2009 113000
1213 2006 145000
1214 2006 134500
1215 2007 125000
1216 2010 112000
1217 2009 229456
1218 2006 80500
1219 2006 91500
1220 2006 115000
1221 2008 134000
1222 2007 143000
1223 2006 137900
1224 2008 184000
1225 2007 145000
1226 2008 214000
1227 2008 147000
1228 2008 367294
1229 2008 127000
1230 2007 190000
1231 2006 132500
1232 2007 101800
1233 2010 142000
1234 2008 130000
1235 2006 138887
1236 2010 175500
1237 2006 195000
1238 2006 142500
1239 2007 265900
1240 2008 224900
1241 2007 248328
1242 2010 170000
1243 2006 465000
1244 2006 230000
1245 2007 178000
1246 2006 186500
1247 2010 169900
1248 2008 129500
1249 2007 119000
1250 2010 244000
1251 2006 171750
1252 2009 130000
1253 2007 294000
1254 2008 165400
1255 2007 127500
1256 2008 301500
1257 2009 99900
1258 2008 190000
1259 2008 151000
1260 2009 181000
1261 2009 128900
1262 2009 161500
1263 2007 180500
1264 2008 181000
1265 2006 183900
1266 2007 122000
1267 2010 378500
1268 2008 381000
1269 2007 144000
1270 2010 260000
1271 2009 185750
1272 2006 137000
1273 2008 177000
1274 2007 139000
1275 2007 137000
1276 2009 162000
1277 2009 197900
1278 2008 237000
1279 2010 68400
1280 2009 227000
1281 2006 180000
1282 2009 150500
1283 2010 139000
1284 2010 169000
1285 2009 132500
1286 2010 143000
1287 2006 190000
1288 2009 278000
1289 2006 281000
1290 2010 180500
1291 2009 119500
1292 2009 107500
1293 2006 162900
1294 2006 115000
1295 2006 138500
1296 2008 155000
1297 2006 140000
1298 2008 160000
1299 2010 154000
1300 2009 225000
1301 2009 177500
1302 2006 290000
1303 2006 232000
1304 2006 130000
1305 2009 325000
1306 2006 202500
1307 2009 138000
1308 2008 147000
1309 2008 179200
1310 2010 335000
1311 2007 203000
1312 2007 302000
1313 2010 333168
1314 2007 119000
1315 2008 206900
1316 2009 295493
1317 2007 208900
1318 2006 275000
1319 2007 111000
1320 2009 156500
1321 2008 72500
1322 2010 190000
1323 2009 82500
1324 2007 147000
1325 2008 55000
1326 2007 79000
1327 2008 130500
1328 2008 256000
1329 2006 176500
1330 2007 227000
1331 2006 132500
1332 2009 100000
1333 2006 125500
1334 2009 125000
1335 2009 167900
1336 2008 135000
1337 2006 52500
1338 2006 200000
1339 2006 128500
1340 2007 123000
1341 2008 155000
1342 2007 228500
1343 2009 177000
1344 2007 155835
1345 2007 108500
1346 2006 262500
1347 2007 283463
1348 2007 215000
1349 2008 122000
1350 2009 200000
1351 2008 171000
1352 2009 134900
1353 2010 410000
1354 2008 235000
1355 2006 170000
1356 2008 110000
1357 2010 149900
1358 2010 177500
1359 2006 315000
1360 2008 189000
1361 2009 260000
1362 2009 104900
1363 2007 156932
1364 2006 144152
1365 2010 216000
1366 2008 193000
1367 2006 127000
1368 2009 144000
1369 2010 232000
1370 2009 105000
1371 2008 165500
1372 2006 274300
1373 2007 466500
1374 2008 250000
1375 2007 239000
1376 2008 91000
1377 2009 117000
1378 2006 83000
1379 2008 167500
1380 2010 58500
1381 2008 237500
1382 2006 157000
1383 2007 112000
1384 2009 105000
1385 2010 125500
1386 2006 250000
1387 2007 136000
1388 2009 377500
1389 2007 131000
1390 2006 235000
1391 2009 124000
1392 2006 123000
1393 2008 163000
1394 2006 246578
1395 2007 281213
1396 2010 160000
1397 2007 137500
1398 2009 138000
1399 2009 137450
1400 2008 120000
1401 2008 193000
1402 2006 193879
1403 2007 282922
1404 2006 105000
1405 2008 275000
1406 2009 133000
1407 2009 112000
1408 2010 125500
1409 2008 215000
1410 2009 230000
1411 2009 140000
1412 2009 90000
1413 2009 257000
1414 2008 207000
1415 2009 175900
1416 2010 122500
1417 2009 340000
1418 2008 124000
1419 2006 223000
1420 2006 179900
1421 2010 127500
1422 2008 136500
1423 2006 274970
1424 2007 144000
1425 2008 142000
1426 2008 271000
1427 2008 140000
1428 2010 119000
1429 2007 182900
1430 2006 192140
1431 2009 143750
1432 2007 64500
1433 2008 186500
1434 2006 160000
1435 2008 174000
1436 2007 120500
1437 2008 394617
1438 2010 149700
1439 2007 197000
1440 2008 191000
1441 2008 149300
1442 2009 310000
1443 2009 121000
1444 2007 179600
1445 2007 129000
1446 2010 157900
1447 2007 240000
1448 2007 112000
1449 2006 92000
1450 2009 136000
1451 2009 287090
1452 2006 145000
1453 2006 84500
1454 2009 185000
1455 2007 175000
1456 2010 210000
1457 2010 266500
1458 2010 142125
1459 2008 147500

export traindf data to an excel file in this directory

In [ ]:
traindf.to_csv('C:/Users/faiz_/Desktop/JupyterNotebook/testdata2022.csv')